name: dbeisinger
favicon: null
layout_spectrum: 0.52658
typography_spectrum: 0.6014331006444991
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#9f9f9f'
    - '#6f6f6f'
    - '#fefefe'
    - '#dcdcdc'
  brandStrength: 0.5
  lightness: 0.744061479344964
  saturation: 0.5
  rhythmicContrast: 0.26709829666651785
purpose: []
