name: dbeisinger
favicon: null
layout_spectrum: 0.9450979495886713
typography_spectrum: 0.6014331006444991
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050505'
    - '#ffffff'
    - '#c9c9c9'
    - '#454545'
    - '#818181'
  brandStrength: 0.5
  lightness: 0.744061479344964
  saturation: 0.5
  rhythmicContrast: 0.26709829666651785
purpose: []
